# docker compose versions
version: '2.2'

# shared volumes
volumes:
  project:

services:

  # mongodb
  mongo:
    image: mongo:3.6
    restart: always

  # Redis
  redis:
    image: redis:alpine
    restart: always

  # web app bundle build
  app:
    image: openneuro/app:${CRN_APP_TAG}
    volumes:
      - project:/srv/packages/openneuro-app/dist
    env_file: ./config.env

  # crn node server
  server:
    image: openneuro/server:${CRN_SERVER_TAG}
    volumes:
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/persistent
    env_file: ./config.env
    depends_on:
      - redis
      - mongo
      - datalad
    restart: always

  # worker
  worker:
    image: openneuro/server:${CRN_SERVER_TAG}
    command:
      - node
      - /srv/worker.js
    volumes:
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/persistent
    env_file: ./config.env
    restart: always

  # datalad Python backend
  datalad:
    image: openneuro/datalad-service:${DATALAD_SERVICE_TAG}
    volumes:
      - ${PERSISTENT_DIR}/datalad:/datalad
      - ./datalad-key:/datalad-key
    env_file: ./config.env
    depends_on:
      - celery
    restart: always
    init: true
  
  # celery Python backend
  celery:
    image: openneuro/datalad-service:${DATALAD_SERVICE_TAG}
    command:
      - celery
      - -A
      - datalad_service.worker
      - worker
      - -Q
      - dataset-worker-0
      - -l
      - info
      - -c
      - "1"
    volumes:
      - ${PERSISTENT_DIR}/datalad:/datalad
      - ./datalad-key:/datalad-key
    restart: always
    env_file: ./config.env
    init: true

  flower:
    image: openneuro/datalad-service:${DATALAD_SERVICE_TAG}
    command:
      - flower
      - -A
      - datalad_service.worker
      - --broker
      - redis://redis
    env_file: ./config.env
    restart: always
    ports:
      - "5555:5555"

  # nginx - static file serving and service proxy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - project:/srv/app/dist
      - ./acme:/acme
      - ${SSL_DIR}:/etc/nginx/ssl
    ports:
      - "80:80"
      - "8110:8110"
      - "443:443"
    depends_on:
      - server
      - datalad
