# docker compose versions
version: '2.2'

# shared volumes
volumes:
  project:
  yarn_cache:

services:
  # web app bundle build
  app:
    build:
      context: .
      dockerfile: ./packages/openneuro-app/Dockerfile
    working_dir: /srv/packages/openneuro-app
    command: sh -c "apk add make gcc g++ python && yarn install && yarn start --watch"
    volumes:
      - .:/srv
      - yarn_cache:/root/.cache
      - project:/srv/packages/openneuro-app/dist
    tmpfs:
      - /srv/node_modules:exec
      - /srv/packages/openneuro-app/node_modules:exec
      - /srv/packages/openneuro-client/node_modules:exec
      - /srv/packages/openneuro-cli/node_modules:exec
      - /srv/packages/openneuro-server/node_modules:exec

  # crn node server
  server:
    build:
      context: ./packages/openneuro-server
    command: sh -c "apk add make gcc g++ python && yarn install && node /srv/index.js"
    volumes:
      - ./packages/openneuro-server:/srv
      - yarn_cache:/root/.cache
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/persistent
    tmpfs:
      - /srv/node_modules:exec

  worker:
    build:
      context: ./packages/openneuro-server
    command: sh -c "apk add make gcc g++ python && yarn install  && node /srv/worker.js"
    volumes:
      - ./packages/openneuro-server:/srv
      - yarn_cache:/root/.cache
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/persistent
    tmpfs:
      - /srv/node_modules:exec

  datalad:
    volumes:
      - ../datalad-service/datalad_service:/datalad_service

  celery:
    volumes:
      - ../datalad-service/datalad_service:/datalad_service
      - ../datalad-service/tests:/tests
    
  # nginx - static file serving and service proxy
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9876:80"
      - "8110:8110"
      - "8443:443"
